runtime: nodejs20
instance_class: F1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
env_variables:
  FIREBASE_CONFIG: '{{
  
}}'
